Artist.find_or_create_by(name: "AJJ")
Artist.find_or_create_by(name: "Apes of the State")
Artist.find_or_create_by(name: "Blackbird Raum")
Artist.find_or_create_by(name: "Broken Bow")
Artist.find_or_create_by(name: "Crampe en Masse")
Artist.find_or_create_by(name: "Days 'n' Daze")
Artist.find_or_create_by(name: "Eric Panic")
Artist.find_or_create_by(name: "Evanescence")
Artist.find_or_create_by(name: "Green Day")
Artist.find_or_create_by(name: "Harley Poe")
Artist.find_or_create_by(name: "Johnny Cash")
Artist.find_or_create_by(name: "Johnny Hobo & The Freight Trains")
Artist.find_or_create_by(name: "Les Cowboys Fringants")
Artist.find_or_create_by(name: "Les Frères à Ch'val")
Artist.find_or_create_by(name: "Les Vulgaires Machins")
Artist.find_or_create_by(name: "Linkin Park")
Artist.find_or_create_by(name: "Matt Pless")
Artist.find_or_create_by(name: "Mumford & Sons")
Artist.find_or_create_by(name: "Pat the Bunny")
Artist.find_or_create_by(name: "Railyard Ghosts")
Artist.find_or_create_by(name: "Ramshackle Glory")
Artist.find_or_create_by(name: "Rise Against")
Artist.find_or_create_by(name: "Simon & Garfunkel")
Artist.find_or_create_by(name: "Slipknot")
Artist.find_or_create_by(name: "Streetlight Manifesto")
Artist.find_or_create_by(name: "Sublime")
Artist.find_or_create_by(name: "The Animals")
Artist.find_or_create_by(name: "The Cat Empire")
Artist.find_or_create_by(name: "Third Eye Blind")
Artist.find_or_create_by(name: "Toh Kay")
Artist.find_or_create_by(name: "We the Heathens")
Artist.find_or_create_by(name: "The Taxpayers")

SongContribution.find_or_create_by(song: Song.find_by(name: "Brave as a Noun"), artist: Artist.find_by(name: "AJJ"))
SongContribution.find_or_create_by(song: Song.find_by(name: "We Shall All Die Alone Someday"), artist: Artist.find_by(name: "AJJ"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Forest Fire"), artist: Artist.find_by(name: "AJJ"))
SongContribution.find_or_create_by(song: Song.find_by(name: "A Song Dedicated to the Memory of Stormy the Rabbit"), artist: Artist.find_by(name: "AJJ"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Love in the Time of Human Papillovirus"), artist: Artist.find_by(name: "AJJ"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Kokopelli Face Tattoo"), artist: Artist.find_by(name: "AJJ"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Bill Collectors' Theme Song"), artist: Artist.find_by(name: "Apes of the State"))
SongContribution.find_or_create_by(song: Song.find_by(name: "I Listened"), artist: Artist.find_by(name: "Apes of the State"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Honey in the Hair"), artist: Artist.find_by(name: "Blackbird Raum"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Coal"), artist: Artist.find_by(name: "Blackbird Raum"))
SongContribution.find_or_create_by(song: Song.find_by(name: "The Helm of Ned Kelly"), artist: Artist.find_by(name: "Blackbird Raum"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Germinal"), artist: Artist.find_by(name: "Blackbird Raum"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Witches"), artist: Artist.find_by(name: "Blackbird Raum"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Silent Spring"), artist: Artist.find_by(name: "Blackbird Raum"))
SongContribution.find_or_create_by(song: Song.find_by(name: "To the Barricades!"), artist: Artist.find_by(name: "Blackbird Raum"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Conquest of Bread"), artist: Artist.find_by(name: "Blackbird Raum"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Lucasville"), artist: Artist.find_by(name: "Blackbird Raum"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Rubicon Drawn"), artist: Artist.find_by(name: "Blackbird Raum"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Plastic Plague"), artist: Artist.find_by(name: "Broken Bow"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Scraps"), artist: Artist.find_by(name: "Broken Bow"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Digitize the Dirt"), artist: Artist.find_by(name: "Broken Bow"))
SongContribution.find_or_create_by(song: Song.find_by(name: "No Earthlings"), artist: Artist.find_by(name: "Broken Bow"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Lights"), artist: Artist.find_by(name: "Broken Bow"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Desolation"), artist: Artist.find_by(name: "Broken Bow"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Wrought Iron Bars"), artist: Artist.find_by(name: "Broken Bow"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Corpus Deorum"), artist: Artist.find_by(name: "Broken Bow"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Berceuse pour les Pas Fins"), artist: Artist.find_by(name: "Crampe en Masse"))
SongContribution.find_or_create_by(song: Song.find_by(name: "None Exempt"), artist: Artist.find_by(name: "Days 'n' Daze"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Empress Bridge"), artist: Artist.find_by(name: "Days 'n' Daze"))
SongContribution.find_or_create_by(song: Song.find_by(name: "The Flatlands"), artist: Artist.find_by(name: "Days 'n' Daze"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Call in the Coroner"), artist: Artist.find_by(name: "Days 'n' Daze"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Show Me the Blueprints"), artist: Artist.find_by(name: "Days 'n' Daze"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Mirror Falls"), artist: Artist.find_by(name: "Days 'n' Daze"))
SongContribution.find_or_create_by(song: Song.find_by(name: "New Gangland"), artist: Artist.find_by(name: "Days 'n' Daze"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Save a Life"), artist: Artist.find_by(name: "Days 'n' Daze"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Like Findin' Needles in a Ballpit"), artist: Artist.find_by(name: "Days 'n' Daze"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Gnargle"), artist: Artist.find_by(name: "Days 'n' Daze"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Soldats de Plomb ou d'Argent"), artist: Artist.find_by(name: "Eric Panic"))
SongContribution.find_or_create_by(song: Song.find_by(name: "My Immortal"), artist: Artist.find_by(name: "Evanescence"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Hitchin' a Ride"), artist: Artist.find_by(name: "Green Day"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Good Riddance (Time of our Lives)"), artist: Artist.find_by(name: "Green Day"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Jesus of Suburbia"), artist: Artist.find_by(name: "Green Day"))
SongContribution.find_or_create_by(song: Song.find_by(name: "What's a Devil to Do"), artist: Artist.find_by(name: "Harley Poe"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Everybody Knows my Name"), artist: Artist.find_by(name: "Harley Poe"))
SongContribution.find_or_create_by(song: Song.find_by(name: "I Am the Living Dead"), artist: Artist.find_by(name: "Harley Poe"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Ouija"), artist: Artist.find_by(name: "Harley Poe"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Vampire's Night Out"), artist: Artist.find_by(name: "Harley Poe"))
SongContribution.find_or_create_by(song: Song.find_by(name: "God's Gonna Cut you Down"), artist: Artist.find_by(name: "Johnny Cash"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Church Hymn for the Condemned"), artist: Artist.find_by(name: "Johnny Hobo & The Freight Trains"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Whiskey Is my Kind of Lullaby"), artist: Artist.find_by(name: "Johnny Hobo & The Freight Trains"))
SongContribution.find_or_create_by(song: Song.find_by(name: "La Cave"), artist: Artist.find_by(name: "Les Cowboys Fringants"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Louis-Hébert"), artist: Artist.find_by(name: "Les Cowboys Fringants"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Sainte Paix"), artist: Artist.find_by(name: "Les Cowboys Fringants"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Le Génie dans la Bouteille"), artist: Artist.find_by(name: "Les Frères à Ch'val"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Être un Comme"), artist: Artist.find_by(name: "Les Vulgaires Machins"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Anéantir le Dogme"), artist: Artist.find_by(name: "Les Vulgaires Machins"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Puits sans Fond"), artist: Artist.find_by(name: "Les Vulgaires Machins"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Compter les Corps"), artist: Artist.find_by(name: "Les Vulgaires Machins"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Shadow of the Day"), artist: Artist.find_by(name: "Linkin Park"))
SongContribution.find_or_create_by(song: Song.find_by(name: "When the Frayed Wind Blows"), artist: Artist.find_by(name: "Matt Pless"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Shots Fired"), artist: Artist.find_by(name: "Matt Pless"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Thistle & Weeds"), artist: Artist.find_by(name: "Mumford & Sons"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Awake my Soul"), artist: Artist.find_by(name: "Mumford & Sons"))
SongContribution.find_or_create_by(song: Song.find_by(name: "The Cave"), artist: Artist.find_by(name: "Mumford & Sons"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Sigh No More"), artist: Artist.find_by(name: "Mumford & Sons"))
SongContribution.find_or_create_by(song: Song.find_by(name: "I'm Going Home"), artist: Artist.find_by(name: "Pat the Bunny"))
SongContribution.find_or_create_by(song: Song.find_by(name: "We Don't Get Tired we Get Even"), artist: Artist.find_by(name: "Pat the Bunny"))
SongContribution.find_or_create_by(song: Song.find_by(name: "I'm Not a Good Person"), artist: Artist.find_by(name: "Pat the Bunny"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Let's Take a Ride like we Used to"), artist: Artist.find_by(name: "Pat the Bunny"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Run from What's Comfortable"), artist: Artist.find_by(name: "Pat the Bunny"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Song for a Netflix Account"), artist: Artist.find_by(name: "Pat the Bunny"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Fear Not"), artist: Artist.find_by(name: "Railyard Ghosts"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Never Coming Home"), artist: Artist.find_by(name: "Ramshackle Glory"))
SongContribution.find_or_create_by(song: Song.find_by(name: "First Song"), artist: Artist.find_by(name: "Ramshackle Glory"))
SongContribution.find_or_create_by(song: Song.find_by(name: "More About Alcoholism"), artist: Artist.find_by(name: "Ramshackle Glory"))
SongContribution.find_or_create_by(song: Song.find_by(name: "We Are All Compost in Training"), artist: Artist.find_by(name: "Ramshackle Glory"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Vampires Are Posers"), artist: Artist.find_by(name: "Ramshackle Glory"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Of Ballots and Barricades"), artist: Artist.find_by(name: "Ramshackle Glory"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Bitter Old Man"), artist: Artist.find_by(name: "Ramshackle Glory"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Your Heart Is a Muscle the Size of Your Fist"), artist: Artist.find_by(name: "Ramshackle Glory"))
SongContribution.find_or_create_by(song: Song.find_by(name: "First Song, Part 2"), artist: Artist.find_by(name: "Ramshackle Glory"))
SongContribution.find_or_create_by(song: Song.find_by(name: "From Here to Utopia"), artist: Artist.find_by(name: "Ramshackle Glory"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Into The Wind"), artist: Artist.find_by(name: "Ramshackle Glory"))
SongContribution.find_or_create_by(song: Song.find_by(name: "The Hand You Reach out is Empty as Is Mine"), artist: Artist.find_by(name: "Ramshackle Glory"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Eulogy For An Adolescence Shattered Against Elliot Street Pavement Heres To Being Young"), artist: Artist.find_by(name: "Ramshackle Glory"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Face The Void"), artist: Artist.find_by(name: "Ramshackle Glory"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Punk Is the Worst Form of Music Except for All the Others"), artist: Artist.find_by(name: "Ramshackle Glory"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Re-Education Through Labor"), artist: Artist.find_by(name: "Rise Against"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Mrs Robinson"), artist: Artist.find_by(name: "Simon & Garfunkel"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Snuff"), artist: Artist.find_by(name: "Slipknot"))
SongContribution.find_or_create_by(song: Song.find_by(name: "The Big Sleep"), artist: Artist.find_by(name: "Streetlight Manifesto"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Forty Days"), artist: Artist.find_by(name: "Streetlight Manifesto"))
SongContribution.find_or_create_by(song: Song.find_by(name: "That'll Be the Day"), artist: Artist.find_by(name: "Streetlight Manifesto"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Here's to Life"), artist: Artist.find_by(name: "Streetlight Manifesto"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Dear Sergio"), artist: Artist.find_by(name: "Streetlight Manifesto"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Would You Be Impressed?"), artist: Artist.find_by(name: "Streetlight Manifesto"))
SongContribution.find_or_create_by(song: Song.find_by(name: "A Moment of Silence/Violence"), artist: Artist.find_by(name: "Streetlight Manifesto"))
SongContribution.find_or_create_by(song: Song.find_by(name: "As the Footsteps Die out Forever"), artist: Artist.find_by(name: "Streetlight Manifesto"))
SongContribution.find_or_create_by(song: Song.find_by(name: "1234 1234"), artist: Artist.find_by(name: "Streetlight Manifesto"))
SongContribution.find_or_create_by(song: Song.find_by(name: "They Provide the Paint for the Picture-Perfect Masterpiece that You Will Paint on the Inside of your Eyelids"), artist: Artist.find_by(name: "Streetlight Manifesto"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Same in the End"), artist: Artist.find_by(name: "Sublime"))
SongContribution.find_or_create_by(song: Song.find_by(name: "House of the Rising Sun"), artist: Artist.find_by(name: "The Animals"))
SongContribution.find_or_create_by(song: Song.find_by(name: "No Longer There"), artist: Artist.find_by(name: "The Cat Empire"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Semi Charmed Life"), artist: Artist.find_by(name: "Third Eye Blind"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Watch it Crash"), artist: Artist.find_by(name: "Toh Kay"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Wolves"), artist: Artist.find_by(name: "We the Heathens"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Wolves II"), artist: Artist.find_by(name: "We the Heathens"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Faith Upon the False"), artist: Artist.find_by(name: "We the Heathens"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Earth Infanticide"), artist: Artist.find_by(name: "We the Heathens"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Where No One Goes"), artist: Artist.find_by(name: "We the Heathens"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Last Ones to Fall"), artist: Artist.find_by(name: "We the Heathens"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Cessation of the Sovereign"), artist: Artist.find_by(name: "We the Heathens"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Lung of Lies"), artist: Artist.find_by(name: "We the Heathens"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Stutter"), artist: Artist.find_by(name: "We the Heathens"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Fallohides"), artist: Artist.find_by(name: "We the Heathens"))
SongContribution.find_or_create_by(song: Song.find_by(name: "The Order"), artist: Artist.find_by(name: "We the Heathens"))
SongContribution.find_or_create_by(song: Song.find_by(name: "To Live in Hell"), artist: Artist.find_by(name: "We the Heathens"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Stealing Apples"), artist: Artist.find_by(name: "The Taxpayers"))
SongContribution.find_or_create_by(song: Song.find_by(name: "Daoly Polizei"), artist: Artist.find_by(name: "Geoff Berner"))
SongContribution.find_or_create_by(song: Song.find_by_name("Daloy Polizei"), artist: Artist.find_or_create_by(name: "Geoff Berner"))
SongContribution.find_or_create_by(song: Song.find_by_name("Seven Nation Army"), artist: Artist.find_or_create_by(name: "The White Stripes"))
SongContribution.find_or_create_by(song: Song.find_by_name("Hell And You"), artist: Artist.find_or_create_by(name: "Amigo The Devil"))
SongContribution.find_or_create_by(song: Song.find_by_name("Two Cups of Tea"), artist: Artist.find_or_create_by(name: "Star Fucking Hipsters"))
SongContribution.find_or_create_by(song: Song.find_by_name("Fallacy of Ruin"), artist: Artist.find_or_create_by(name: "Atrocity Solution"))
SongContribution.find_or_create_by(song: Song.find_by_name("Fragments"), artist: Artist.find_or_create_by(name: "an Unkindness"))
SongContribution.find_or_create_by(song: Song.find_by_name("Toxicity"), artist: Artist.find_or_create_by(name: "System of a Down"))
SongContribution.find_or_create_by(song: Song.find_by_name("Silver Lining"), artist: Artist.find_or_create_by(name: "Doom Scroll"))
SongContribution.find_or_create_by(song: Song.find_by_name("Pastime Paradise"), artist: Artist.find_or_create_by(name: "Stevie Wonder"))
SongContribution.find_or_create_by(song: Song.find_by_name("I Am the Antichrist to You"), artist: Artist.find_or_create_by(name: "Kishi Bashi"))
SongContribution.find_or_create_by(song: Song.find_by_name("Bringin' Home the Rain"), artist: Artist.find_or_create_by(name: "The Builders and the Butchers"))
SongContribution.find_or_create_by(song: Song.find_by_name("Cricket"), artist: Artist.find_or_create_by(name: "Dance Hall Crashers"))
SongContribution.find_or_create_by(song: Song.find_by_name("Auntie Earth"), artist: Artist.find_or_create_by(name: "Walter Mitty and his Makeshift Orchestra"))
SongContribution.find_or_create_by(song: Song.find_by_name("Booger Storm"), artist: Artist.find_or_create_by(name: "Walter Mitty and his Makeshift Orchestra"))
SongContribution.find_or_create_by(song: Song.find_by_name("Breathe Funny"), artist: Artist.find_or_create_by(name: "Walter Mitty and his Makeshift Orchestra"))
SongContribution.find_or_create_by(song: Song.find_by_name("Howl"), artist: Artist.find_or_create_by(name: "Walter Mitty and his Makeshift Orchestra"))
SongContribution.find_or_create_by(song: Song.find_by_name("Proudhon in Manhattan"), artist: Artist.find_or_create_by(name: "Wingnut Dishwashers Union"))
SongContribution.find_or_create_by(song: Song.find_by_name("Chamomile"), artist: Artist.find_or_create_by(name: "Walter Mitty and his Makeshift Orchestra"))
SongContribution.find_or_create_by(song: Song.find_by_name("Gorehound"), artist: Artist.find_or_create_by(name: "Harley Poe"))
SongContribution.find_or_create_by(song: Song.find_by_name("Old Kentucky Breakdown"), artist: Artist.find_or_create_by(name: "Broken Bow"))
SongContribution.find_or_create_by(song: Song.find_by_name("Checkmate"), artist: Artist.find_or_create_by(name: "Broken Bow"))
SongContribution.find_or_create_by(song: Song.find_by_name("Forever Yours"), artist: Artist.find_or_create_by(name: "Dirty Harry"))
SongContribution.find_or_create_by(song: Song.find_by_name("Tickin' Time"), artist: Artist.find_or_create_by(name: "Dirty Harry"))
SongContribution.find_or_create_by(song: Song.find_by_name("Shadow & Blood"), artist: Artist.find_or_create_by(name: "Rent Strike"))
SongContribution.find_or_create_by(song: Song.find_by_name("There is a time"), artist: Artist.find_or_create_by(name: "The Dillards"))
SongContribution.find_or_create_by(song: Song.find_by_name("Este Infierno"), artist: Artist.find_or_create_by(name: "Bestiärio"))
SongContribution.find_or_create_by(song: Song.find_by_name("Salgo a la Calle"), artist: Artist.find_or_create_by(name: "Elektroduendes"))
SongContribution.find_or_create_by(song: Song.find_by_name("Plus Rien"), artist: Artist.find_or_create_by(name: "Les Cowboys Fringants"))
SongContribution.find_or_create_by(song: Song.find_by_name("Ya no sos igual"), artist: Artist.find_or_create_by(name: "2 Minutos"))
SongContribution.find_or_create_by(song: Song.find_by_name("I. Snowdrop"), artist: Artist.find_or_create_by(name: "Rent Strike"))
SongContribution.find_or_create_by(song: Song.find_by_name("Devil's Will"), artist: Artist.find_or_create_by(name: "Cousin Boneless"))
SongContribution.find_or_create_by(song: Song.find_by_name("Tangled in Ropes"), artist: Artist.find_or_create_by(name: "Holy Locust"))
SongContribution.find_or_create_by(song: Song.find_by_name("Crabe"), artist: Artist.find_or_create_by(name: "Les Goules"))
SongContribution.find_or_create_by(song: Song.find_by_name("Frijolero"), artist: Artist.find_or_create_by(name: "Molotov"))
SongContribution.find_or_create_by(song: Song.find_by_name("Where is my Mind?"), artist: Artist.find_or_create_by(name: "The Pixies"))
SongContribution.find_or_create_by(song: Song.find_by_name("Porque te vas"), artist: Artist.find_or_create_by(name: "Attaque 77"))
SongContribution.find_or_create_by(song: Song.find_by_name("Somewhere over the rainbow"), artist: Artist.find_or_create_by(name: "Israel Kamakawiwo'ole"))
SongContribution.find_or_create_by(song: Song.find_by_name("California Dreamin'"), artist: Artist.find_or_create_by(name: "The Mamas & The Papas"))
SongContribution.find_or_create_by(song: Song.find_by_name("Careless Whisper"), artist: Artist.find_or_create_by(name: "George Michael"))
SongContribution.find_or_create_by(song: Song.find_by_name("Ram Ranch"), artist: Artist.find_or_create_by(name: "Grant MacDonald"))
SongContribution.find_or_create_by(song: Song.find_by_name("Caca en la cabeza"), artist: Artist.find_or_create_by(name: "Sofía Viola"))
SongContribution.find_or_create_by(song: Song.find_by_name("Deja de Llorar"), artist: Artist.find_or_create_by(name: "El Polaco"))
SongContribution.find_or_create_by(song: Song.find_by_name("Toune d'Automne"), artist: Artist.find_or_create_by(name: "Les Cowboys Fringants"))
SongContribution.find_or_create_by(song: Song.find_by_name("Salut les Amoureux"), artist: Artist.find_or_create_by(name: "Joe Dassin"))
SongContribution.find_or_create_by(song: Song.find_by_name("Ça va pas changer le monde"), artist: Artist.find_or_create_by(name: "Joe Dassin"))
SongContribution.find_or_create_by(song: Song.find_by_name("Wagon wheel"), artist: Artist.find_or_create_by(name: "Darius Rucker"))
SongContribution.find_or_create_by(song: Song.find_by_name("En berne"), artist: Artist.find_or_create_by(name: "Les Cowboys Fringants"))
SongContribution.find_or_create_by(song: Song.find_by_name("Joyeux calvaire"), artist: Artist.find_or_create_by(name: "Les Cowboys Fringants"))
SongContribution.find_or_create_by(song: Song.find_by_name("Mon chum Rémi"), artist: Artist.find_or_create_by(name: "Les Cowboys Fringants"))
SongContribution.find_or_create_by(song: Song.find_by_name("L'hiver approche"), artist: Artist.find_or_create_by(name: "Les Cowboys Fringants"))
SongContribution.find_or_create_by(song: Song.find_by_name("Hannah"), artist: Artist.find_or_create_by(name: "Les Cowboys Fringants"))
SongContribution.find_or_create_by(song: Song.find_by_name("Sur mon épaule"), artist: Artist.find_or_create_by(name: "Les Cowboys Fringants"))
SongContribution.find_or_create_by(song: Song.find_by_name("Unchained Melody"), artist: Artist.find_or_create_by(name: "The Righteous Brothers"))
SongContribution.find_or_create_by(song: Song.find_by_name("The Sound of Silence"), artist: Artist.find_or_create_by(name: "Simon & Garfunkel"))
SongContribution.find_or_create_by(song: Song.find_by_name("Pieces"), artist: Artist.find_or_create_by(name: "Sum 41"))
SongContribution.find_or_create_by(song: Song.find_by_name("Stand by Me"), artist: Artist.find_or_create_by(name: "Ben E. King"))
SongContribution.find_or_create_by(song: Song.find_by_name("Welcome to my Life"), artist: Artist.find_or_create_by(name: "Simple Plan"))
SongContribution.find_or_create_by(song: Song.find_by_name("Country Roads"), artist: Artist.find_or_create_by(name: "John Denver"))
SongContribution.find_or_create_by(song: Song.find_by_name("Everytime we Touch"), artist: Artist.find_or_create_by(name: "Cascada"))
SongContribution.find_or_create_by(song: Song.find_by_name("Dust in the Wind"), artist: Artist.find_or_create_by(name: "Kansas"))
SongContribution.find_or_create_by(song: Song.find_by_name("Dirty Paws"), artist: Artist.find_or_create_by(name: "Of Monsters and Men"))
SongContribution.find_or_create_by(song: Song.find_by_name("King and Lionheart"), artist: Artist.find_or_create_by(name: "Of Monsters and Men"))
SongContribution.find_or_create_by(song: Song.find_by_name("Fake Plastic Trees"), artist: Artist.find_or_create_by(name: "Radiohead"))
SongContribution.find_or_create_by(song: Song.find_by_name("Hotel California"), artist: Artist.find_or_create_by(name: "The Eagles"))
SongContribution.find_or_create_by(song: Song.find_by_name("Iris"), artist: Artist.find_or_create_by(name: "Goo Goo Dolls"))
SongContribution.find_or_create_by(song: Song.find_by_name("Ces Temps-Ci"), artist: Artist.find_or_create_by(name: "Les Cowboys Fringants"))
SongContribution.find_or_create_by(song: Song.find_by_name("Banlieue"), artist: Artist.find_or_create_by(name: "Les Cowboys Fringants"))
SongContribution.find_or_create_by(song: Song.find_by_name("Les Étoiles Filantes"), artist: Artist.find_or_create_by(name: "Les Cowboys Fringants"))
SongContribution.find_or_create_by(song: Song.find_by_name("Belle"), artist: Artist.find_or_create_by(name: "Notre-Dame de Paris"))
SongContribution.find_or_create_by(song: Song.find_by_name("The Way"), artist: Artist.find_or_create_by(name: "Fastball"))
SongContribution.find_or_create_by(song: Song.find_by_name("Wonderwall"), artist: Artist.find_or_create_by(name: "Oasis"))
SongContribution.find_or_create_by(song: Song.find_by_name("Mala Fortuna"), artist: Artist.find_or_create_by(name: "Bestiärio"))
SongContribution.find_or_create_by(song: Song.find_by_name("Avispa/Oso"), artist: Artist.find_or_create_by(name: "Bestiärio"))
SongContribution.find_or_create_by(song: Song.find_by_name("I Will Survive"), artist: Artist.find_or_create_by(name: "Gloria Gaynor (Cake Cover)"))
SongContribution.find_or_create_by(song: Song.find_by_name("Total Eclipse of the Heart"), artist: Artist.find_or_create_by(name: "Bonnie Tyler"))
SongContribution.find_or_create_by(song: Song.find_by_name("Creep"), artist: Artist.find_or_create_by(name: "Radiohead"))
SongContribution.find_or_create_by(song: Song.find_by_name("Don't Speak"), artist: Artist.find_or_create_by(name: "No Doubt"))
SongContribution.find_or_create_by(song: Song.find_by_name("Au Pays des Sapins Géants"), artist: Artist.find_or_create_by(name: "Les Cowboys Fringants"))
SongContribution.find_or_create_by(song: Song.find_by_name("When It's Gone"), artist: Artist.find_or_create_by(name: "We The Heathens"))
SongContribution.find_or_create_by(song: Song.find_by_name("Que Ardan"), artist: Artist.find_or_create_by(name: "Bestiärio"))
SongContribution.find_or_create_by(song: Song.find_by_name("Here's to the Mayans"), artist: Artist.find_or_create_by(name: "We The Heathens"))
SongContribution.find_or_create_by(song: Song.find_by_name("Promesas de Sinceridad"), artist: Artist.find_or_create_by(name: "Bestiärio"))
