# artists
Artist.create_or_find_by(name: "AJJ")
Artist.create_or_find_by(name: "Apes of the State")
Artist.create_or_find_by(name: "Blackbird Raum")
Artist.create_or_find_by(name: "Broken Bow")
Artist.create_or_find_by(name: "Crampe en Masse")
Artist.create_or_find_by(name: "Days 'n' Daze")
Artist.create_or_find_by(name: "Eric Panic")
Artist.create_or_find_by(name: "Evanescence")
Artist.create_or_find_by(name: "Green Day")
Artist.create_or_find_by(name: "Harley Poe")
Artist.create_or_find_by(name: "Johnny Cash")
Artist.create_or_find_by(name: "Johnny Hobo & The Freight Trains")
Artist.create_or_find_by(name: "Les Cowboys Fringants")
Artist.create_or_find_by(name: "Les Frères à Ch'val")
Artist.create_or_find_by(name: "Les Vulgaires Machins")
Artist.create_or_find_by(name: "Linkin Park")
Artist.create_or_find_by(name: "Matt Pless")
Artist.create_or_find_by(name: "Mumford & Sons")
Artist.create_or_find_by(name: "Pat the Bunny")
Artist.create_or_find_by(name: "Railyard Ghosts")
Artist.create_or_find_by(name: "Ramshackle Glory")
Artist.create_or_find_by(name: "Rise Against")
Artist.create_or_find_by(name: "Simon & Garfunkel")
Artist.create_or_find_by(name: "Slipknot")
Artist.create_or_find_by(name: "Streetlight Manifesto")
Artist.create_or_find_by(name: "Sublime")
Artist.create_or_find_by(name: "The Animals")
Artist.create_or_find_by(name: "The Cat Empire")
Artist.create_or_find_by(name: "Third Eye Blind")
Artist.create_or_find_by(name: "Toh Kay")
Artist.create_or_find_by(name: "We the Heathens")
Artist.create_or_find_by(name: "The Taxpayers")

# song contributions
SongContribution.create_or_find_by(song: Song.find_by(name: "Brave as a Noun"), artist: Artist.find_by(name: "AJJ"))
SongContribution.create_or_find_by(song: Song.find_by(name: "We Shall All Die Alone Someday"), artist: Artist.find_by(name: "AJJ"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Forest Fire"), artist: Artist.find_by(name: "AJJ"))
SongContribution.create_or_find_by(song: Song.find_by(name: "A Song Dedicated to the Memory of Stormy the Rabbit"), artist: Artist.find_by(name: "AJJ"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Love in the Time of Human Papillovirus"), artist: Artist.find_by(name: "AJJ"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Kokopelli Face Tattoo"), artist: Artist.find_by(name: "AJJ"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Bill Collectors' Theme Song"), artist: Artist.find_by(name: "Apes of the State"))
SongContribution.create_or_find_by(song: Song.find_by(name: "I Listened"), artist: Artist.find_by(name: "Apes of the State"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Honey in the Hair"), artist: Artist.find_by(name: "Blackbird Raum"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Coal"), artist: Artist.find_by(name: "Blackbird Raum"))
SongContribution.create_or_find_by(song: Song.find_by(name: "The Helm of Ned Kelly"), artist: Artist.find_by(name: "Blackbird Raum"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Germinal"), artist: Artist.find_by(name: "Blackbird Raum"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Witches"), artist: Artist.find_by(name: "Blackbird Raum"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Silent Spring"), artist: Artist.find_by(name: "Blackbird Raum"))
SongContribution.create_or_find_by(song: Song.find_by(name: "To the Barricades!"), artist: Artist.find_by(name: "Blackbird Raum"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Conquest of Bread"), artist: Artist.find_by(name: "Blackbird Raum"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Lucasville"), artist: Artist.find_by(name: "Blackbird Raum"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Rubicon Drawn"), artist: Artist.find_by(name: "Blackbird Raum"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Plastic Plague"), artist: Artist.find_by(name: "Broken Bow"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Scraps"), artist: Artist.find_by(name: "Broken Bow"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Digitize the Dirt"), artist: Artist.find_by(name: "Broken Bow"))
SongContribution.create_or_find_by(song: Song.find_by(name: "No Earthlings"), artist: Artist.find_by(name: "Broken Bow"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Lights"), artist: Artist.find_by(name: "Broken Bow"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Desolation"), artist: Artist.find_by(name: "Broken Bow"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Wrought Iron Bars"), artist: Artist.find_by(name: "Broken Bow"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Corpus Deorum"), artist: Artist.find_by(name: "Broken Bow"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Berceuse pour les Pas Fins"), artist: Artist.find_by(name: "Crampe en Masse"))
SongContribution.create_or_find_by(song: Song.find_by(name: "None Exempt"), artist: Artist.find_by(name: "Days 'n' Daze"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Empress Bridge"), artist: Artist.find_by(name: "Days 'n' Daze"))
SongContribution.create_or_find_by(song: Song.find_by(name: "The Flatlands"), artist: Artist.find_by(name: "Days 'n' Daze"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Call in the Coroner"), artist: Artist.find_by(name: "Days 'n' Daze"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Show Me the Blueprints"), artist: Artist.find_by(name: "Days 'n' Daze"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Mirror Falls"), artist: Artist.find_by(name: "Days 'n' Daze"))
SongContribution.create_or_find_by(song: Song.find_by(name: "New Gangland"), artist: Artist.find_by(name: "Days 'n' Daze"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Save a Life"), artist: Artist.find_by(name: "Days 'n' Daze"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Like Findin' Needles in a Ballpit"), artist: Artist.find_by(name: "Days 'n' Daze"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Gnargle"), artist: Artist.find_by(name: "Days 'n' Daze"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Soldats de Plomb ou d'Argent"), artist: Artist.find_by(name: "Eric Panic"))
SongContribution.create_or_find_by(song: Song.find_by(name: "My Immortal"), artist: Artist.find_by(name: "Evanescence"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Hitchin' a Ride"), artist: Artist.find_by(name: "Green Day"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Good Riddance (Time of our Lives)"), artist: Artist.find_by(name: "Green Day"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Jesus of Suburbia"), artist: Artist.find_by(name: "Green Day"))
SongContribution.create_or_find_by(song: Song.find_by(name: "What's a Devil to Do"), artist: Artist.find_by(name: "Harley Poe"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Everybody Knows my Name"), artist: Artist.find_by(name: "Harley Poe"))
SongContribution.create_or_find_by(song: Song.find_by(name: "I Am the Living Dead"), artist: Artist.find_by(name: "Harley Poe"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Ouija"), artist: Artist.find_by(name: "Harley Poe"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Vampire's Night Out"), artist: Artist.find_by(name: "Harley Poe"))
SongContribution.create_or_find_by(song: Song.find_by(name: "God's Gonna Cut you Down"), artist: Artist.find_by(name: "Johnny Cash"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Church Hymn for the Condemned"), artist: Artist.find_by(name: "Johnny Hobo & The Freight Trains"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Whiskey Is my Kind of Lullaby"), artist: Artist.find_by(name: "Johnny Hobo & The Freight Trains"))
SongContribution.create_or_find_by(song: Song.find_by(name: "La Cave"), artist: Artist.find_by(name: "Les Cowboys Fringants"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Louis-Hébert"), artist: Artist.find_by(name: "Les Cowboys Fringants"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Sainte Paix"), artist: Artist.find_by(name: "Les Cowboys Fringants"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Le Génie dans la Bouteille"), artist: Artist.find_by(name: "Les Frères à Ch'val"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Être un Comme"), artist: Artist.find_by(name: "Les Vulgaires Machins"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Anéantir le Dogme"), artist: Artist.find_by(name: "Les Vulgaires Machins"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Puits sans Fond"), artist: Artist.find_by(name: "Les Vulgaires Machins"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Compter les Corps"), artist: Artist.find_by(name: "Les Vulgaires Machins"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Shadow of the Day"), artist: Artist.find_by(name: "Linkin Park"))
SongContribution.create_or_find_by(song: Song.find_by(name: "When the Frayed Wind Blows"), artist: Artist.find_by(name: "Matt Pless"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Shots Fired"), artist: Artist.find_by(name: "Matt Pless"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Thistle & Weeds"), artist: Artist.find_by(name: "Mumford & Sons"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Awake my Soul"), artist: Artist.find_by(name: "Mumford & Sons"))
SongContribution.create_or_find_by(song: Song.find_by(name: "The Cave"), artist: Artist.find_by(name: "Mumford & Sons"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Sigh No More"), artist: Artist.find_by(name: "Mumford & Sons"))
SongContribution.create_or_find_by(song: Song.find_by(name: "I'm Going Home"), artist: Artist.find_by(name: "Pat the Bunny"))
SongContribution.create_or_find_by(song: Song.find_by(name: "We Don't Get Tired we Get Even"), artist: Artist.find_by(name: "Pat the Bunny"))
SongContribution.create_or_find_by(song: Song.find_by(name: "I'm Not a Good Person"), artist: Artist.find_by(name: "Pat the Bunny"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Let's Take a Ride like we Used to"), artist: Artist.find_by(name: "Pat the Bunny"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Run from What's Comfortable"), artist: Artist.find_by(name: "Pat the Bunny"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Song for a Netflix Account"), artist: Artist.find_by(name: "Pat the Bunny"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Fear Not"), artist: Artist.find_by(name: "Railyard Ghosts"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Never Coming Home"), artist: Artist.find_by(name: "Ramshackle Glory"))
SongContribution.create_or_find_by(song: Song.find_by(name: "First Song"), artist: Artist.find_by(name: "Ramshackle Glory"))
SongContribution.create_or_find_by(song: Song.find_by(name: "More About Alcoholism"), artist: Artist.find_by(name: "Ramshackle Glory"))
SongContribution.create_or_find_by(song: Song.find_by(name: "We Are All Compost in Training"), artist: Artist.find_by(name: "Ramshackle Glory"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Vampires Are Posers"), artist: Artist.find_by(name: "Ramshackle Glory"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Of Ballots and Barricades"), artist: Artist.find_by(name: "Ramshackle Glory"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Bitter Old Man"), artist: Artist.find_by(name: "Ramshackle Glory"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Your Heart Is a Muscle the Size of Your Fist"), artist: Artist.find_by(name: "Ramshackle Glory"))
SongContribution.create_or_find_by(song: Song.find_by(name: "First Song, Part 2"), artist: Artist.find_by(name: "Ramshackle Glory"))
SongContribution.create_or_find_by(song: Song.find_by(name: "From Here to Utopia"), artist: Artist.find_by(name: "Ramshackle Glory"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Into The Wind"), artist: Artist.find_by(name: "Ramshackle Glory"))
SongContribution.create_or_find_by(song: Song.find_by(name: "The Hand You Reach out is Empty as Is Mine"), artist: Artist.find_by(name: "Ramshackle Glory"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Eulogy For An Adolescence Shattered Against Elliot Street Pavement Heres To Being Young"), artist: Artist.find_by(name: "Ramshackle Glory"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Face The Void"), artist: Artist.find_by(name: "Ramshackle Glory"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Punk Is the Worst Form of Music Except for All the Others"), artist: Artist.find_by(name: "Ramshackle Glory"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Re-Education Through Labor"), artist: Artist.find_by(name: "Rise Against"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Mrs Robinson"), artist: Artist.find_by(name: "Simon & Garfunkel"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Snuff"), artist: Artist.find_by(name: "Slipknot"))
SongContribution.create_or_find_by(song: Song.find_by(name: "The Big Sleep"), artist: Artist.find_by(name: "Streetlight Manifesto"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Forty Days"), artist: Artist.find_by(name: "Streetlight Manifesto"))
SongContribution.create_or_find_by(song: Song.find_by(name: "That'll Be the Day"), artist: Artist.find_by(name: "Streetlight Manifesto"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Here's to Life"), artist: Artist.find_by(name: "Streetlight Manifesto"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Dear Sergio"), artist: Artist.find_by(name: "Streetlight Manifesto"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Would You Be Impressed?"), artist: Artist.find_by(name: "Streetlight Manifesto"))
SongContribution.create_or_find_by(song: Song.find_by(name: "A Moment of Silence/Violence"), artist: Artist.find_by(name: "Streetlight Manifesto"))
SongContribution.create_or_find_by(song: Song.find_by(name: "As the Footsteps Die out Forever"), artist: Artist.find_by(name: "Streetlight Manifesto"))
SongContribution.create_or_find_by(song: Song.find_by(name: "1234 1234"), artist: Artist.find_by(name: "Streetlight Manifesto"))
SongContribution.create_or_find_by(song: Song.find_by(name: "They Provide the Paint for the Picture-Perfect Masterpiece that You Will Paint on the Inside of your Eyelids"), artist: Artist.find_by(name: "Streetlight Manifesto"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Same in the End"), artist: Artist.find_by(name: "Sublime"))
SongContribution.create_or_find_by(song: Song.find_by(name: "House of the Rising Sun"), artist: Artist.find_by(name: "The Animals"))
SongContribution.create_or_find_by(song: Song.find_by(name: "No Longer There"), artist: Artist.find_by(name: "The Cat Empire"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Semi Charmed Life"), artist: Artist.find_by(name: "Third Eye Blind"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Watch it Crash"), artist: Artist.find_by(name: "Toh Kay"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Wolves"), artist: Artist.find_by(name: "We the Heathens"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Wolves II"), artist: Artist.find_by(name: "We the Heathens"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Faith Upon the False"), artist: Artist.find_by(name: "We the Heathens"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Earth Infanticide"), artist: Artist.find_by(name: "We the Heathens"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Where No One Goes"), artist: Artist.find_by(name: "We the Heathens"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Last Ones to Fall"), artist: Artist.find_by(name: "We the Heathens"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Cessation of the Sovereign"), artist: Artist.find_by(name: "We the Heathens"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Lung of Lies"), artist: Artist.find_by(name: "We the Heathens"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Stutter"), artist: Artist.find_by(name: "We the Heathens"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Fallohides"), artist: Artist.find_by(name: "We the Heathens"))
SongContribution.create_or_find_by(song: Song.find_by(name: "The Order"), artist: Artist.find_by(name: "We the Heathens"))
SongContribution.create_or_find_by(song: Song.find_by(name: "To Live in Hell"), artist: Artist.find_by(name: "We the Heathens"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Stealing Apples"), artist: Artist.find_by(name: "The Taxpayers"))
