# artists
Artist.create_or_find_by(name: "Geoff Berner")
Artist.create_or_find_by(name: "Zella Day (White Stripes Cover)")
Artist.create_or_find_by(name: "Amigo The Devil")
Artist.create_or_find_by(name: "Star Fucking Hipsters")
Artist.create_or_find_by(name: "Atrocity Solution")
Artist.create_or_find_by(name: "An Unkindness")
Artist.create_or_find_by(name: "System Of A Down")
Artist.create_or_find_by(name: "Doom Scroll ")
Artist.create_or_find_by(name: "Stevie Wonder")
Artist.create_or_find_by(name: "Kishi Bashi")
Artist.create_or_find_by(name: "The Builders and the Butchers")
Artist.create_or_find_by(name: "Walter Mitty and his Makeshift Orchestra")
Artist.create_or_find_by(name: "Wingnut Dishwashers Union")
Artist.create_or_find_by(name: "Harley Poe")
Artist.create_or_find_by(name: "Broken Bow")
Artist.create_or_find_by(name: "Dirty Harry")
Artist.create_or_find_by(name: "Rent Strike!")
Artist.create_or_find_by(name: "The Dillards")
Artist.create_or_find_by(name: "Bestiärio")

# song contributions
SongContribution.create_or_find_by(song: Song.find_by(name: "Daloy Polizei"), artist: Artist.find_by(name: "Geoff Berner"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Seven Nation Army"), artist: Artist.find_by(name: "Zella Day (White Stripes Cover)"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Hell And You"), artist: Artist.find_by(name: "Amigo The Devil"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Two Cups of Tea"), artist: Artist.find_by(name: "Star Fucking Hipsters"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Fallacy of Ruin"), artist: Artist.find_by(name: "Atrocity Solution"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Fragments"), artist: Artist.find_by(name: "An Unkindness"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Toxicity"), artist: Artist.find_by(name: "System Of A Down"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Silver Lining"), artist: Artist.find_by(name: "Doom Scroll "))
SongContribution.create_or_find_by(song: Song.find_by(name: "Pastime Paradise"), artist: Artist.find_by(name: "Stevie Wonder"))
SongContribution.create_or_find_by(song: Song.find_by(name: "I Am the Antichrist to You"), artist: Artist.find_by(name: "Kishi Bashi"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Bringin' Home the Rain"), artist: Artist.find_by(name: "The Builders and the Butchers"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Cricket"), artist: Artist.find_by(name: "The Builders and the Butchers"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Auntie Earth"), artist: Artist.find_by(name: "Walter Mitty and his Makeshift Orchestra"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Booger Storm"), artist: Artist.find_by(name: "Walter Mitty and his Makeshift Orchestra"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Breathe Funny"), artist: Artist.find_by(name: "Walter Mitty and his Makeshift Orchestra"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Howl"), artist: Artist.find_by(name: "Walter Mitty and his Makeshift Orchestra"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Proudhon in Manhattan"), artist: Artist.find_by(name: "Wingnut Dishwashers Union"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Chamomile"), artist: Artist.find_by(name: "Walter Mitty and his Makeshift Orchestra"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Gorehound"), artist: Artist.find_by(name: "Harley Poe"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Old Kentucky Breakdown"), artist: Artist.find_by(name: "Broken Bow"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Checkmate"), artist: Artist.find_by(name: "Broken Bow"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Forever Yours"), artist: Artist.find_by(name: "Dirty Harry"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Tickin' Time"), artist: Artist.find_by(name: "Dirty Harry"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Shadow & Blood"), artist: Artist.find_by(name: "Rent Strike!"))
SongContribution.create_or_find_by(song: Song.find_by(name: "There is a time"), artist: Artist.find_by(name: "The Dillards"))
SongContribution.create_or_find_by(song: Song.find_by(name: "Este Infierno"), artist: Artist.find_by(name: "Bestiärio"))
