begin
    pl.play({song_id: 20, played_at: Time.now - 2.days}, 6)
    pl.play({song_id: 13, played_at: Time.now - 3.days}, 5)
    pl.play({song_id: 138, played_at: Time.now - 4.days}, 4)
    pl.play({song_id: 148, played_at: Time.now - 4.days}, 8)
    pl.play({song_id: 9, played_at: Time.now - 3.days}, 1)
    pl.play({song_id: 136, played_at: Time.now - 5.days}, 4)
    pl.play({song_id: 22, played_at: Time.now - 3.days}, 4)
    pl.play({song_id: 144, played_at: Time.now - 5.days}, 2)
    pl.play({song_id: 123, played_at: Time.now - 4.days}, 2)
    pl.play({song_id: 145, played_at: Time.now - 8.days}, 2)
    pl.play({song_id: 44, played_at: Time.now - 5.days}, 5)
    pl.play({song_id: 23, played_at: Time.now - 7.days}, 2)
    pl.play({song_id: 147, played_at: Time.now - 7.days}, 6)
    pl.play({song_id: 110, played_at: Time.now - 11.days}, 3)
    pl.play({song_id: 102, played_at: Time.now - 15.days}, 2)
    pl.play({song_id: 125, played_at: Time.now - 18.days}, 2)
    pl.play({song_id: 121, played_at: Time.now - 4.days}, 8)
    pl.play({song_id: 164, played_at: Time.now - 3.days}, 10)
    pl.play({song_id: 149, played_at: Time.now - 8.days}, 2)
    pl.play({song_id: 117, played_at: Time.now - 3.days}, 3)
end
