namespace :sync do
    desc "update the number of song plays, one shot thing"
    task :plays => [:environment] do |task|
        song_play = Song.find_by_id(1).last_play(User.first)
        song_play&.update(played_at: "2024-01-26 17:49:04 UTC")
        song_play = Song.find_by_id(2).last_play(User.first)
        song_play&.update(played_at: "2024-03-05 22:31:21 UTC")
        song_play = Song.find_by_id(3).last_play(User.first)
        song_play&.update(played_at: "2024-03-05 22:32:45 UTC")
        song_play = Song.find_by_id(4).last_play(User.first)
        song_play&.update(played_at: "2024-01-27 01:58:29 UTC")
        song_play = Song.find_by_id(5).last_play(User.first)
        song_play&.update(played_at: "2024-02-09 23:05:54 UTC")
        song_play = Song.find_by_id(6).last_play(User.first)
        song_play&.update(played_at: "2024-02-03 20:25:16 UTC")
        song_play = Song.find_by_id(7).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(8).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(9).last_play(User.first)
        song_play&.update(played_at: "2024-02-16 20:21:54 UTC")
        song_play = Song.find_by_id(10).last_play(User.first)
        song_play&.update(played_at: "2024-02-12 22:55:54 UTC")
        song_play = Song.find_by_id(11).last_play(User.first)
        song_play&.update(played_at: "2024-01-29 23:46:50 UTC")
        song_play = Song.find_by_id(12).last_play(User.first)
        song_play&.update(played_at: "2024-02-29 00:40:59 UTC")
        song_play = Song.find_by_id(13).last_play(User.first)
        song_play&.update(played_at: "2024-02-09 23:01:36 UTC")
        song_play = Song.find_by_id(14).last_play(User.first)
        song_play&.update(played_at: "2020-08-07 00:00:00 UTC")
        song_play = Song.find_by_id(15).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(16).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(17).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(18).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(19).last_play(User.first)
        song_play&.update(played_at: "2024-01-29 23:33:50 UTC")
        song_play = Song.find_by_id(20).last_play(User.first)
        song_play&.update(played_at: "2024-02-11 22:03:39 UTC")
        song_play = Song.find_by_id(21).last_play(User.first)
        song_play&.update(played_at: "2024-02-17 19:45:01 UTC")
        song_play = Song.find_by_id(22).last_play(User.first)
        song_play&.update(played_at: "2024-01-27 01:47:56 UTC")
        song_play = Song.find_by_id(23).last_play(User.first)
        song_play&.update(played_at: "2024-02-20 00:34:43 UTC")
        song_play = Song.find_by_id(24).last_play(User.first)
        song_play&.update(played_at: "2024-02-29 00:37:48 UTC")
        song_play = Song.find_by_id(25).last_play(User.first)
        song_play&.update(played_at: "2024-03-07 23:07:30 UTC")
        song_play = Song.find_by_id(26).last_play(User.first)
        song_play&.update(played_at: "2024-02-03 20:44:56 UTC")
        song_play = Song.find_by_id(27).last_play(User.first)
        song_play&.update(played_at: "2024-01-29 23:30:57 UTC")
        song_play = Song.find_by_id(28).last_play(User.first)
        song_play&.update(played_at: "2020-12-09 00:00:00 UTC")
        song_play = Song.find_by_id(29).last_play(User.first)
        song_play&.update(played_at: "2024-01-27 15:44:54 UTC")
        song_play = Song.find_by_id(30).last_play(User.first)
        song_play&.update(played_at: "2024-02-05 22:41:25 UTC")
        song_play = Song.find_by_id(31).last_play(User.first)
        song_play&.update(played_at: "2020-09-09 00:00:00 UTC")
        song_play = Song.find_by_id(32).last_play(User.first)
        song_play&.update(played_at: "2020-07-29 00:00:00 UTC")
        song_play = Song.find_by_id(33).last_play(User.first)
        song_play&.update(played_at: "2020-07-29 00:00:00 UTC")
        song_play = Song.find_by_id(34).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(35).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(36).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(37).last_play(User.first)
        song_play&.update(played_at: "2024-01-25 05:17:27 UTC")
        song_play = Song.find_by_id(38).last_play(User.first)
        song_play&.update(played_at: "2020-07-30 00:00:00 UTC")
        song_play = Song.find_by_id(39).last_play(User.first)
        song_play&.update(played_at: "2024-01-26 17:55:12 UTC")
        song_play = Song.find_by_id(40).last_play(User.first)
        song_play&.update(played_at: "2024-02-09 23:25:28 UTC")
        song_play = Song.find_by_id(41).last_play(User.first)
        song_play&.update(played_at: "2024-01-29 23:42:39 UTC")
        song_play = Song.find_by_id(42).last_play(User.first)
        song_play&.update(played_at: "2020-08-07 00:00:00 UTC")
        song_play = Song.find_by_id(43).last_play(User.first)
        song_play&.update(played_at: "2024-01-26 18:17:38 UTC")
        song_play = Song.find_by_id(44).last_play(User.first)
        song_play&.update(played_at: "2024-02-29 22:43:27 UTC")
        song_play = Song.find_by_id(45).last_play(User.first)
        song_play&.update(played_at: "2024-02-28 00:22:01 UTC")
        song_play = Song.find_by_id(46).last_play(User.first)
        song_play&.update(played_at: "2024-01-29 23:28:24 UTC")
        song_play = Song.find_by_id(47).last_play(User.first)
        song_play&.update(played_at: "2024-01-26 18:13:49 UTC")
        song_play = Song.find_by_id(48).last_play(User.first)
        song_play&.update(played_at: "2024-02-03 20:22:04 UTC")
        song_play = Song.find_by_id(49).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(50).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(51).last_play(User.first)
        song_play&.update(played_at: "2020-07-30 00:00:00 UTC")
        song_play = Song.find_by_id(52).last_play(User.first)
        song_play&.update(played_at: "2020-11-08 00:00:00 UTC")
        song_play = Song.find_by_id(53).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(54).last_play(User.first)
        song_play&.update(played_at: "2024-03-07 23:10:51 UTC")
        song_play = Song.find_by_id(55).last_play(User.first)
        song_play&.update(played_at: "2020-11-08 00:00:00 UTC")
        song_play = Song.find_by_id(56).last_play(User.first)
        song_play&.update(played_at: "2020-07-30 00:00:00 UTC")
        song_play = Song.find_by_id(57).last_play(User.first)
        song_play&.update(played_at: "2020-07-30 00:00:00 UTC")
        song_play = Song.find_by_id(58).last_play(User.first)
        song_play&.update(played_at: "2024-02-17 19:28:52 UTC")
        song_play = Song.find_by_id(59).last_play(User.first)
        song_play&.update(played_at: "2024-02-29 22:33:25 UTC")
        song_play = Song.find_by_id(60).last_play(User.first)
        song_play&.update(played_at: "2024-02-05 22:22:57 UTC")
        song_play = Song.find_by_id(61).last_play(User.first)
        song_play&.update(played_at: "2020-09-09 00:00:00 UTC")
        song_play = Song.find_by_id(62).last_play(User.first)
        song_play&.update(played_at: "2024-03-05 22:40:34 UTC")
        song_play = Song.find_by_id(63).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(64).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(65).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(66).last_play(User.first)
        song_play&.update(played_at: "2024-02-29 22:35:34 UTC")
        song_play = Song.find_by_id(67).last_play(User.first)
        song_play&.update(played_at: "2024-02-17 19:33:30 UTC")
        song_play = Song.find_by_id(68).last_play(User.first)
        song_play&.update(played_at: "2020-08-03 00:00:00 UTC")
        song_play = Song.find_by_id(69).last_play(User.first)
        song_play&.update(played_at: "2024-02-08 00:27:35 UTC")
        song_play = Song.find_by_id(70).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(71).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(72).last_play(User.first)
        song_play&.update(played_at: "2024-01-29 23:37:37 UTC")
        song_play = Song.find_by_id(73).last_play(User.first)
        song_play&.update(played_at: "2024-03-07 23:03:29 UTC")
        song_play = Song.find_by_id(74).last_play(User.first)
        song_play&.update(played_at: "2024-02-09 22:53:12 UTC")
        song_play = Song.find_by_id(75).last_play(User.first)
        song_play&.update(played_at: "2020-08-25 00:00:00 UTC")
        song_play = Song.find_by_id(76).last_play(User.first)
        song_play&.update(played_at: "2024-02-04 23:48:46 UTC")
        song_play = Song.find_by_id(77).last_play(User.first)
        song_play&.update(played_at: "2020-08-25 00:00:00 UTC")
        song_play = Song.find_by_id(78).last_play(User.first)
        song_play&.update(played_at: "2024-03-06 22:42:18 UTC")
        song_play = Song.find_by_id(79).last_play(User.first)
        song_play&.update(played_at: "2024-03-05 22:36:18 UTC")
        song_play = Song.find_by_id(80).last_play(User.first)
        song_play&.update(played_at: "2020-08-25 00:00:00 UTC")
        song_play = Song.find_by_id(81).last_play(User.first)
        song_play&.update(played_at: "2024-02-09 22:56:06 UTC")
        song_play = Song.find_by_id(82).last_play(User.first)
        song_play&.update(played_at: "2020-08-25 00:00:00 UTC")
        song_play = Song.find_by_id(83).last_play(User.first)
        song_play&.update(played_at: "2024-01-27 01:39:10 UTC")
        song_play = Song.find_by_id(84).last_play(User.first)
        song_play&.update(played_at: "2024-01-27 01:55:03 UTC")
        song_play = Song.find_by_id(85).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(86).last_play(User.first)
        song_play&.update(played_at: "2024-02-05 22:31:33 UTC")
        song_play = Song.find_by_id(87).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(88).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(89).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(90).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(91).last_play(User.first)
        song_play&.update(played_at: "2024-02-28 00:05:37 UTC")
        song_play = Song.find_by_id(92).last_play(User.first)
        song_play&.update(played_at: "2024-02-04 23:47:40 UTC")
        song_play = Song.find_by_id(93).last_play(User.first)
        song_play&.update(played_at: "2020-08-04 00:00:00 UTC")
        song_play = Song.find_by_id(94).last_play(User.first)
        song_play&.update(played_at: "2020-08-04 00:00:00 UTC")
        song_play = Song.find_by_id(95).last_play(User.first)
        song_play&.update(played_at: "2020-09-09 00:00:00 UTC")
        song_play = Song.find_by_id(96).last_play(User.first)
        song_play&.update(played_at: "2024-02-11 22:03:42 UTC")
        song_play = Song.find_by_id(97).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(98).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(99).last_play(User.first)
        song_play&.update(played_at: "2024-02-08 00:25:26 UTC")
        song_play = Song.find_by_id(100).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(101).last_play(User.first)
        song_play&.update(played_at: "2024-02-29 22:43:21 UTC")
        song_play = Song.find_by_id(102).last_play(User.first)
        song_play&.update(played_at: "2024-02-28 00:06:21 UTC")
        song_play = Song.find_by_id(103).last_play(User.first)
        song_play&.update(played_at: "2020-09-16 00:00:00 UTC")
        song_play = Song.find_by_id(104).last_play(User.first)
        song_play&.update(played_at: "2024-02-17 19:38:27 UTC")
        song_play = Song.find_by_id(105).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(106).last_play(User.first)
        song_play&.update(played_at: "2024-02-17 19:24:49 UTC")
        song_play = Song.find_by_id(107).last_play(User.first)
        song_play&.update(played_at: "2024-02-29 00:45:34 UTC")
        song_play = Song.find_by_id(108).last_play(User.first)
        song_play&.update(played_at: "2020-08-22 00:00:00 UTC")
        song_play = Song.find_by_id(109).last_play(User.first)
        song_play&.update(played_at: "2024-03-06 22:37:24 UTC")
        song_play = Song.find_by_id(110).last_play(User.first)
        song_play&.update(played_at: "2024-01-27 02:09:12 UTC")
        song_play = Song.find_by_id(111).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(112).last_play(User.first)
        song_play&.update(played_at: "2024-02-08 00:21:36 UTC")
        song_play = Song.find_by_id(113).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(114).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(115).last_play(User.first)
        song_play&.update(played_at: "2024-02-05 22:37:46 UTC")
        song_play = Song.find_by_id(116).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(117).last_play(User.first)
        song_play&.update(played_at: "2024-02-05 22:13:29 UTC")
        song_play = Song.find_by_id(118).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(119).last_play(User.first)
        song_play&.update(played_at: "2024-02-09 23:19:13 UTC")
        song_play = Song.find_by_id(120).last_play(User.first)
        song_play&.update(played_at: "2024-02-23 19:11:15 UTC")
        song_play = Song.find_by_id(121).last_play(User.first)
        song_play&.update(played_at: "2024-02-28 00:27:27 UTC")
        song_play = Song.find_by_id(122).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(123).last_play(User.first)
        song_play&.update(played_at: "2024-03-05 22:28:47 UTC")
        song_play = Song.find_by_id(124).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(125).last_play(User.first)
        song_play&.update(played_at: "2024-02-23 19:15:02 UTC")
        song_play = Song.find_by_id(126).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(127).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(128).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(129).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(130).last_play(User.first)
        song_play&.update(played_at: "2024-03-07 23:16:58 UTC")
        song_play = Song.find_by_id(131).last_play(User.first)
        song_play&.update(played_at: "2024-01-25 18:07:41 UTC")
        song_play = Song.find_by_id(132).last_play(User.first)
        song_play&.update(played_at: "2024-02-03 20:17:07 UTC")
        song_play = Song.find_by_id(133).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(134).last_play(User.first)
        song_play&.update(played_at: "2024-02-03 20:15:17 UTC")
        song_play = Song.find_by_id(135).last_play(User.first)
        song_play&.update(played_at: "2024-02-03 20:41:25 UTC")
        song_play = Song.find_by_id(136).last_play(User.first)
        song_play&.update(played_at: "2024-02-20 00:41:48 UTC")
        song_play = Song.find_by_id(137).last_play(User.first)
        song_play&.update(played_at: "2024-01-25 18:23:53 UTC")
        song_play = Song.find_by_id(138).last_play(User.first)
        song_play&.update(played_at: "2024-03-05 22:44:09 UTC")
        song_play = Song.find_by_id(139).last_play(User.first)
        song_play&.update(played_at: "2024-02-04 23:37:29 UTC")
        song_play = Song.find_by_id(140).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(141).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(142).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(143).last_play(User.first)
        song_play&.update(played_at: "2024-02-28 00:09:24 UTC")
        song_play = Song.find_by_id(144).last_play(User.first)
        song_play&.update(played_at: "2024-02-03 20:32:32 UTC")
        song_play = Song.find_by_id(145).last_play(User.first)
        song_play&.update(played_at: "2024-03-06 22:50:48 UTC")
        song_play = Song.find_by_id(146).last_play(User.first)
        song_play&.update(played_at: "2024-01-31 00:02:35 UTC")
        song_play = Song.find_by_id(147).last_play(User.first)
        song_play&.update(played_at: "2024-03-05 22:49:04 UTC")
        song_play = Song.find_by_id(148).last_play(User.first)
        song_play&.update(played_at: "2024-02-23 18:54:07 UTC")
        song_play = Song.find_by_id(149).last_play(User.first)
        song_play&.update(played_at: "2024-03-06 22:47:25 UTC")
        song_play = Song.find_by_id(150).last_play(User.first)
        song_play&.update(played_at: "2024-02-16 20:09:50 UTC")
        song_play = Song.find_by_id(151).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(152).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(153).last_play(User.first)
        song_play&.update(played_at: "2024-02-16 20:19:33 UTC")
        song_play = Song.find_by_id(154).last_play(User.first)
        song_play&.update(played_at: "2024-02-16 20:13:35 UTC")
        song_play = Song.find_by_id(155).last_play(User.first)
        song_play&.update(played_at: "2024-01-30 23:49:14 UTC")
        song_play = Song.find_by_id(156).last_play(User.first)
        song_play&.update(played_at: "2024-03-07 23:20:21 UTC")
        song_play = Song.find_by_id(157).last_play(User.first)
        song_play&.update(played_at: "2024-02-28 00:17:43 UTC")
        song_play = Song.find_by_id(158).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(159).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(160).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(161).last_play(User.first)
        song_play&.update(played_at: "2024-02-17 19:41:50 UTC")
        song_play = Song.find_by_id(162).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(163).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(164).last_play(User.first)
        song_play&.update(played_at: "2024-03-07 23:25:01 UTC")
        song_play = Song.find_by_id(165).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(166).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(167).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(168).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(169).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(170).last_play(User.first)
        song_play&.update(played_at: nil)
        song_play = Song.find_by_id(171).last_play(User.first)
        song_play&.update(played_at: "2024-01-27 15:56:19 UTC")
        song_play = Song.find_by_id(172).last_play(User.first)
        song_play&.update(played_at: "2024-02-28 00:13:03 UTC")
        song_play = Song.find_by_id(173).last_play(User.first)
        song_play&.update(played_at: "2024-03-05 22:45:47 UTC")
    end
end
